const mocksHistorias = [
  {
    id: 0,
    nombre: "Amazon",
    titulo: "¿Millonario vendiendo libros?",
    img:
      "https://s.libertaddigital.com/2014/02/04/1920/1080/fit/amazon-bezos16102013.jpg",
    contenido: [
      "Jeff nació en Alburquerque en 1964, cuatro años más tarde su padre los abandonó y su madre se casó con un inmigrante cubano llamado Miguel «Mike» Bezos cuya familia provenía de Villafrechós (Valladolid). Desde los 3 años, su madre se empeñó en que estudiara en una escuela Montessori, al igual que lo hicieron los fundadores de Google, fundador de la Wikipedia o, incluso, Henry Ford. Años más tardes, Bezos decidió estudiar ingeniería electrónica y comunicación en Princeton y cuando se licenció decidió trasladarse a Nueva York para trabajar en Wall Street. Una de las empresas en las que estuvo trabajando fue D.E. Shaw & Co, uno de los fondos más importantes del momento y con tan solo 26 años ya era vicepresidente.",

      "Pero Jeff Bezos era una persona con actitud muy inquieta y curiosa, en 1994 leyendo un informe, descubrió que el uso de Internet había crecido un 2300% solamente ese año… y pensó: «tengo que estar ahí», por lo que se puso manos a la obra para descubrir con qué tipo de negocio debía involucrarse. Así que hizo una lista de 20 productos que las personas de a pie compraríamos con frecuencia y vio que vender libros era la mejor opción por precio y universalidad. No perdió el tiempo, se lo comentó a su pareja y se fueron juntos en coche a Seattle, por el camino escribió lo que sería su primer plan de negocios.Jeff le pidió dinero a sus padres y le dieron $300.000 de los ahorros que tenían para la jubilación. Con ese dinero instalaron la primera oficina en el garaje de su casa en Seattle con 4 trabajadores.  Intentó poner varios nombres diferentes a la empresa pero su abogado se los rechazó por sonar demasiado siniestros. Así que Jeff cogió el diccionario y decidió llamar a su empresa como el río Amazon, porque era exótico y sonaba majestuoso. Finalmente en 1995 la web amazon.com se lanza y de forma muy rápida, tan solo unos pocos meses después, reciben una inversión de $8 millones de KPCB, así que Amazon salió a bolsa y KPCB multiplicó por 55.000%… Realmente increíble.",

      "Tan solo en sus dos primeros meses de vida, Amazon vendió en 45 países e ingresaba unos $20.000/semana.  Pero no se acabó aquí, hay que tener en cuenta que eran los tiempos de la burbuja puntocom, de modo que tan solo dos años después, el 15 mayo de 1997, empezó a cotizar en NASDAQ a un precio de $18.00 por acción, y desde el primer día el precio se disparó. Haciendo posible que Amazon se diversificara unos pocos meses después, añadiendo a la compra de libros, los CDs, DVDs, videojuegos, ropa. Sin embargo, pese a todo este masivo crecimiento, el fundador de Amazon no era un hombre de muchas pretensiones, y se puede ver como sus oficinas eran un cuchitril en un barrio chungo de Seattle, de hecho en el programa 60 minutos en 1999 el entrevistador le pregunta a Bezos por su triste escritorio y este contesta: «Sólo gastamos dinero en lo que importa realmente.» Lo más importante que tuvo el fundador de Amazon fue su afán de superación, en concreto Bezos tenía varias obsesiones para escalar la empresa y una de ellas fue clave. Tenían que dominar (ser grandes) rápidamente. De hecho, Amazon entró en beneficios",
    ],
    contenidoImg: [
      "https://s1.eestatic.com/2019/03/17/actualidad/Actualidad_383974555_130487890_1000x667.jpg",

      "https://resizer.codigounico.com/resizer/resizer.php?imagen=https://www.codigounico.com/wp-content/uploads/sites/2/2018/10/jeff-bezos-asi-es-el-hombre-mas-rico-del-mundo-y-de-la-historia-2.jpg&nuevoancho=750&crop=0",
      "https://images-na.ssl-images-amazon.com/images/G/01/gc/designs/livepreview/amazon_dkblue_noto_email_v2016_us-main._CB468775337_.png",
    ],

    url:
      "https://www.multiplicalia.com/fundador-de-amazon-jeff-bezos/#:~:text=El%20fundador%20de%20Amazon%2C%20la%20historia%20de%20Jeff%20Bezos&text=Jeff%20naci%C3%B3%20en%20Alburquerque%20en,proven%C3%ADa%20de%20Villafrech%C3%B3s%20(Valladolid).",
  },
  {
    id: 1,
    nombre: "KFC",
    titulo: "El Coronel Sanders y el éxito de KFC",
    img:
      "https://tentulogo.com/wp-content/uploads/2018/10/Cabecera-coronel-sanders-1.jpg",
    contenido: [
      "Harland Sanders, mejor conocido como Coronel Sanders, nació un 9 de septiembre de 1890. Sanders fue el hijo mayor de 3 hermanos que nacieron en el seno de una humilde familia de Henryville (Indiana), la cual tenía ascendencia irlandesa. Su padre falleció cuando él tenía 5 años, por lo que tuvo que, desde muy joven, aprender a cocinar y trabajar: abandonó la escuela a los 12 años para ayudar con las tareas en la granja de la familia y, poco tiempo después, después de sufrir malos tratos por parte de su padrastro, se mudó a casa de sus tíos, quienes vivían en la cercana ciudad de New Albany (Indiana).Se dice que, a la edad de 15 años, falsificó su certificado de nacimiento para alistarse en el ejército de los Estados Unidos, que siempre ha representado una oportunidad relativamente sencilla para poder salir de la pobreza, pues el gobierno te ofrece un sueldo y educación a cambio de que defiendas al país, cosa que además te da cierto prestigio. Completó los compromisos del servicio militar en la isla Cuba, y después se trasladó a Alabama, donde contrajo matrimonio con Josephine King y tuvo 3 hijos Estudió leyes por correspondencia, mientras tuvo todo tipo de empleos: bombero en ferrocarriles, corredor de seguros, operador de un bote de vapor en un río de Ohio, vendedor de llantas, etc. Pero el trabajo que más le acomodó entonces fue el de las gasolineras o estaciones de servicio. Ocupó varios puestos en diferentes gasolineras del centro de los Estados Unidos hasta que abrió una propia en la pequeña ciudad de Corbin, al sureste del estado de Kentucky.",

      " Para este momento, el Harland contaba con 40 años de edad y fue a esta edad que comenzó a ser pionero en varias cosas: Lo primero que hizo fue ofrecer un servicio de comidas para los viajeros que paraban a recargar combustible en su gasolinera; pensó que cada vez se hacían viajes más largos y que podía ser buen negocio vender también combustible para el cuerpo cansado. En ese sentido, Harland creó el concepto de “estación de servicio”, que ahora es replicable en prácticamente todas las gasolineras del mundo. En ese entonces no tenía un restaurant propiamente dicho, ni siquiera tenía un menú, sino que servía a sus clientes en su propia mesa de comedor las cosas que tenía disponibles en ese momento, por lo general alimentos que pudieran ser preparados rápidamente o que fueran fácilmente conservables: lonchas de jamón campestre y pollo frito. Este invento suyo de la estación de servicio y además su talento para la cocina, lo hicieron popular en la zona al punto de que el gobernador de Kentucky de ese entonces, Ruby Laffoon, lo nombró “Coronel del Kentucky”, como reconocimiento a su contribución en el ámbito de la gastronomía lugareña. Esa popularidad, a su vez, se estaba traduciendo en muchas visitas a su estación de servicio, por lo que ya una simple mesa de comedor no le bastaba para atender a todos los que querían probar sus deliciosas creaciones. Eso lo impulsó, un año después de abrir el establecimiento, a lanzarse de lleno a montar un restaurant adjunto, con un menú de varios platillos y con espacio y mesas para 142 comensales. En este lugar fue donde comenzó a preparar su famoso pollo frito a partir de una receta propia que consta de 11 hierbas y especias, receta que patentó en 1940 y que ha permanecido secreta hasta ahora. (Existe un reporte del Chicago Tribune de que un supuesto sobrino del Coronel Sanders llamado Joe Ledington, reveló la receta secreta, aunque no hay un aval oficial de esto más que el testimonio del hombre). Esta receta fue la estrella del menú, y esto lo llevó a concentrarse en ella y perfeccionarla, descubriendo luego que tendría potencial para un negocio más grande. Para 1952 (a los 62 años) había reunido suficiente dinero para abrir un restaurante en la ciudad de Salt Lake City (Utah), con el nombre de Kentucky Fried Chicken. Entonces, por todo el centro de los Estados Unidos se comentaba sobre la fama que tenía el pollo frito en ese estado, por lo que un nombre así era lógicamente atractivo para todo el mundo; pero nadie se imaginó que su popularidad iría como una bola de nieve hasta ser lo que es ahora. La imagen del Coronel Sanders era bastante atractiva en muchos sentidos, un señor de bigote canoso y un traje completamente blanco con corbata negra que podía ser “el tío” o “el abuelo” de cualquiera, una imagen de familia que ayudó mucho a la compañía a fijarse en la clase media pujante que estaba extendiéndose por todo Estados Unidos.",

      "Para 1974 tenía 600 establecimientos con su producto en los Estados Unidos y Canadá. Ese mismo año, al no poder manejar humanamente el nivel de negocio que estaba suponiendo Kentucky Fried Chicken, vendió sus acciones de Estados Unidos por 2 millones de dólares a un grupo de inversionistas entre los que se encontraba John Brown Jr., quien más tarde fungiría como gobernador de Kentucky. Además, la compañía le ofreció un salario vitalicio de 40.000 dólares anuales (que posteriormente aumentó a 200.000 USD) para que siguiera siendo embajador y relacionista público de Kentucky Fried Chicken hasta el día de su muerte. Entonces se dedicó a recorrer el país promocionando la marca. En 1976 una encuesta independiente lo nombró como la “segunda celebridad más reconocida a nivel mundial”. En 1970 abandonó el consejo de dirección de Kentucky Fired Chicken, pero continuó siendo la imagen publicitaria, mientras que la empresa aumentaba su presencia en Estados Unidos, Puerto Rico y algunos países como México, Japón, Bahamas, Jamaica y posteriormente Colombia.El Coronel Sanders falleció a la de edad de los 90 años, en 1980, víctima de una leucemia aguda que le había sido detectada 6 meses antes del fatídico hecho. Fue sepultado con su atuendo característico en el cementerio de Corbin (Kentucky). En su honor, los nuevos propietarios mantuvieron su rostro como identificativo de Kentucky Fired Chicken, marca que hoy en día es una de las que mayor presencia tiene en el mundo.",
    ],
    contenidoImg: [
      "https://estaeslahistoria.com/wp-content/uploads/2019/08/historia-de-kfc-18.jpg",
      "https://www.mercadonegro.pe/wp-content/uploads/2020/01/maxresdefault-1.jpg",
      "https://mktadstrategies.files.wordpress.com/2020/02/kfc-logo.png?w=1024",
    ],
    url:
      "https://tentulogo.com/la-inspiradora-historia-del-coronel-sanders-fundador-de-kfc-a-los-62-anos/",
  },
  {
    id: 2,
    nombre: "ElonMusk",
    titulo: "Inicios y éxito de Elon Musk",
    img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQbollMfPEWeWVrhqXiVjz5uEw7AXkb4mBXYW_cyXZ3eZ52sCpt&usqp=CAU",
    contenido: [
      "Elon Musk nació en 1971 en Sudáfrica. Su madre es la modelo y dietista Maye Musk, y su padre, Errol Musk, un ingeniero electromecánico, a quien Elon ha descrito como 'un ser humano terrible'. Elon Reeve Musk es el mayor de los tres hijos de la familia, y es ciudadano de tres países: Sudáfrica, Canadá y Estados Unidos. Musk pasó su infancia con la nariz metida en libros y computadoras. Fue un niño pequeño e introvertido, condenado al ostracismo por sus compañeros de escuela y regularmente golpeado por los grandulones de la clase. Pero en su adolescencia, él mismo creció lo suficiente y muy aceleradamente, así que pudo defenderse. Musk se mudó a Silicon Valley en el verano de 1995. Se inscribió en un programa de doctorado en Física Aplicada en la Universidad de Stanford, pero se retiró después de solo dos días. Su hermano Kimball Musk, 15 meses más joven que Elon, acababa de graduarse de la Universidad de Queen con un título en finanzas, y se unió a él en California. La Internet temprana despegaba, y los hermanos decidieron lanzar una empresa startup a la cual llamaron Zip2. Era una especie de directorio de negocios en línea, equipado con mapas. Con el tiempo, los hermanos encontraron inversionistas para Zip2 y la convirtieron en una compañía exitosa. En 1999, los hermanos vendieron Zip2 al fabricante de computadoras Compaq por 307 millones de dólares. Luego, Elon fundó por su cuenta una compañía de servicios financieros en línea: X.com. Su principal rival era una empresa llamada Confinity, fundada por Peter Thiel y dos socios, tan solo unos meses después de X.com. Ambas tenían sus oficinas en el mismo edificio. Las dos compañías se fusionaron en marzo de 2000 y tomaron el nombre de su producto principal, PayPal, un servicio de transferencia de dinero en línea, de persona a persona. Ebay, el servicio de subastas en línea, compró PayPal en octubre de 2002, a cambio de acciones de Ebay por un valor de 1.500 millones de dólares. ",

      " A la edad de 31 años, Elon Musk, quien había sido el mayor accionista de PayPal, con el 11.7 por ciento de las acciones, se hizo dueño de 165 millones de dólares en acciones de Ebay. Las compañías que Elon Musk fundó, cofundó y/o dirigió desde que abandonó PayPal --dos de las cuales son SpaceX y Tesla Motors, en las cuales arriesgó toda su fortuna--, se centran en abordar tres dilemas distintos a largo plazo para la humanidad a largo plazo: el riesgo climático, el riesgo de la dependencia de un solo planeta y el riesgo de obsolescencia de la especie humana Tesla Motors, SolarCity y The Boring Company tienen como objetivo abordar el riesgo climático acelerando la transición a la electricidad limpia y al transporte eléctrico. Según Musk, la supervivencia de la Humanidad está en riesgo a largo plazo si se limita solo a este planeta. Tarde o temprano, algún desastre, tal vez un asteroide, un supervolcán o una guerra nuclear, terminará nuestra existencia en la Tierra. Musk fundó Space Exploration Technologies Corp., o SpaceX, en mayo de 2002, con el objetivo de sacar a los seres humanos del planeta. Musk aprendió por sí mismo las habilidades de ingeniería necesarias para diseñar cohetes, y es director de tecnología y CEO de SpaceX. Una contratación clave al principio fue la undécima empleada en unirse: Gwynne Shotwell, encargada del desarrollo comercial. Ella pronto se estableció como brazo derecho de Musk en SpaceX. Se ha convertido en una leyenda en el mundo de la tecnología espacial, y la compañía bien podría haber fallado sin ella.",

      "Musk y otros pensadores dicen que las superinteligencias generales artificiales (AGSI), es decir, las inteligencias generales de máquinas más inteligentes que los seres humanos, presentarán un enorme riesgo existencial para el futuro de la humanidad. Es por eso que, en diciembre de 2015, cofundó la compañía sin fines de lucro OpenAI para desarrollar una 'IA amigable'. OpenAI proporciona acceso gratuito a sus resultados avanzados de investigación de IA; la idea es difundir técnicas para hacer que AGSI sea seguro y evitar que grupos poderosos monopolicen AGSI. Elon Musk no es un héroe perfecto e infalible. Es un creador brillante de visión y capacidad extraordinarias, pero también es, según algunos ex empleados, un hombre muy difícil para trabajar. Trabaja 80 horas a la semana, y espera que sus ingenieros también mantengan ese horario.A menudo es impaciente con sus compañeros de trabajo, y cuando está estresado, a veces despide a las personas en el acto por lo que considera muestras de supuesta incompetencia que otros considerarían como errores muy menores.En sus comunicados, Musk ha cometido varios errores de juicio, a veces enviando tweets incendiarios por los que luego tuvo que disculparse (tuitea mucho). En mayo de 2020, Musk resistió una intensa controversia sobre su decisión de reabrir la planta de fabricación de Tesla Motors en Fremont, California, después de un cierre de dos meses. Musk reaccionaba con el cierre a las declaraciones de un funcionario del condado de Alameda que dictaminó que Tesla no era un 'negocio esencial' que y debía permanecer cerrado debido al confinamiento por el SARS-CoV-2 en la región. Pese a estas y otras controversias y comentarios públicos mal formulados, ha habido pocos errores importantes de Elon Musk en la ejecución de su negocio principal. Dado que Tesla y SpaceX han resistido sus frágiles años de crecimiento temprano, y ahora están en camino de convertirse en consorcios plenamente consolidados, no aparecen obstáculos visibles que pudieran frenar a Elon Musk, mientras el empresario se empeña por llevar a sus compañías, literalmente, hasta las estrellas.",
    ],
    contenidoImg: [
      "https://media.vandal.net/i/715x402/2-2018/2018214174348_1.jpg",
      "https://www.valoraanalitik.com/wp-content/uploads/2020/02/Tesla-fotoMercuryNews.jpg",
      "https://www.dw.com/image/48296207_303.jpg",
    ],

    url:
      "https://www.dw.com/es/qui%C3%A9n-es-elon-musk-y-c%C3%B3mo-logr%C3%B3-su-%C3%A9xito/a-53598536#:~:text=Musk%20fund%C3%B3%20Space%20Exploration%20Technologies,tecnolog%C3%ADa%20y%20CEO%20de%20SpaceX.",
  },
];

export default mocksHistorias;
